#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-2-Clause
"""Generate exhaustive C/Nim constant and enum value assertions.

Usage: tools/generate_value_test.py bgfx.nim bgfx/defines.nim tests/test_values.nim
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


CONSTANT = re.compile(r"^  (?P<name>BGFX_[A-Z0-9_]+)\*\s*=")
ENUM = re.compile(r"^    (?P<name>BGFX_[A-Z0-9_]+)\s*=\s*")
EXPECTED_CONSTANTS = 350
EXPECTED_ENUM_VALUES = 444

HELPERS = (
    ("BGFX_STATE_ALPHA_REF", "0x5a"),
    ("BGFX_STATE_POINT_SIZE", "7"),
    ("BGFX_STENCIL_FUNC_REF", "0x6b"),
    ("BGFX_STENCIL_FUNC_RMASK", "0x8c"),
    ("BGFX_SAMPLER_BORDER_COLOR", "9"),
    (
        "BGFX_STATE_BLEND_FUNC_SEPARATE",
        "BGFX_STATE_BLEND_SRC_ALPHA, BGFX_STATE_BLEND_INV_SRC_ALPHA, "
        "BGFX_STATE_BLEND_ONE, BGFX_STATE_BLEND_ZERO",
    ),
    (
        "BGFX_STATE_BLEND_EQUATION_SEPARATE",
        "BGFX_STATE_BLEND_EQUATION_ADD, BGFX_STATE_BLEND_EQUATION_REVSUB",
    ),
    (
        "BGFX_STATE_BLEND_FUNC",
        "BGFX_STATE_BLEND_SRC_ALPHA, BGFX_STATE_BLEND_INV_SRC_ALPHA",
    ),
    ("BGFX_STATE_BLEND_EQUATION", "BGFX_STATE_BLEND_EQUATION_SUB"),
    (
        "BGFX_STATE_BLEND_FUNC_RT_x",
        "BGFX_STATE_BLEND_SRC_ALPHA, BGFX_STATE_BLEND_INV_SRC_ALPHA",
    ),
    (
        "BGFX_STATE_BLEND_FUNC_RT_xE",
        "BGFX_STATE_BLEND_ONE, BGFX_STATE_BLEND_ZERO, BGFX_STATE_BLEND_EQUATION_MAX",
    ),
    (
        "BGFX_STATE_BLEND_FUNC_RT_1",
        "BGFX_STATE_BLEND_SRC_ALPHA, BGFX_STATE_BLEND_INV_SRC_ALPHA",
    ),
    (
        "BGFX_STATE_BLEND_FUNC_RT_2",
        "BGFX_STATE_BLEND_SRC_ALPHA, BGFX_STATE_BLEND_INV_SRC_ALPHA",
    ),
    (
        "BGFX_STATE_BLEND_FUNC_RT_3",
        "BGFX_STATE_BLEND_SRC_ALPHA, BGFX_STATE_BLEND_INV_SRC_ALPHA",
    ),
    (
        "BGFX_STATE_BLEND_FUNC_RT_1E",
        "BGFX_STATE_BLEND_ONE, BGFX_STATE_BLEND_ZERO, BGFX_STATE_BLEND_EQUATION_MAX",
    ),
    (
        "BGFX_STATE_BLEND_FUNC_RT_2E",
        "BGFX_STATE_BLEND_ONE, BGFX_STATE_BLEND_ZERO, BGFX_STATE_BLEND_EQUATION_MAX",
    ),
    (
        "BGFX_STATE_BLEND_FUNC_RT_3E",
        "BGFX_STATE_BLEND_ONE, BGFX_STATE_BLEND_ZERO, BGFX_STATE_BLEND_EQUATION_MAX",
    ),
)


def names(pattern: re.Pattern[str], source: str) -> list[str]:
    return [match.group("name") for line in source.splitlines() if (match := pattern.match(line))]


def generate(constants: list[str], enum_values: list[str]) -> str:
    if len(constants) != EXPECTED_CONSTANTS:
        raise ValueError(f"expected {EXPECTED_CONSTANTS} constants, found {len(constants)}")
    if len(enum_values) != EXPECTED_ENUM_VALUES:
        raise ValueError(
            f"expected {EXPECTED_ENUM_VALUES} enum values, found {len(enum_values)}"
        )

    lines = [
        "# SPDX-License-Identifier: BSD-2-Clause",
        "# Generated by tools/generate_value_test.py. Do not edit by hand.",
        "",
        "import bgfx",
        "",
        '{.emit: """',
        "#include <stdint.h>",
        "#include <bgfx/c99/bgfx.h>",
        "#if defined(__cplusplus)",
        "# define BGFXIM_STATIC_ASSERT(condition, message) static_assert(condition, message)",
        "#else",
        "# define BGFXIM_STATIC_ASSERT(condition, message) _Static_assert(condition, message)",
        "#endif",
        '""".}',
        "",
    ]

    for index, name in enumerate(constants + enum_values):
        value_name = f"nimValue{index}"
        lines.extend(
            [
                f"const {value_name} = uint64({name})",
                "{.emit: [\"BGFXIM_STATIC_ASSERT((uint64_t)("
                f"{name}) == \", {value_name}, "
                f"\", \\\"value mismatch: {name}\\\");\"].}}",
            ]
        )

    helper_offset = len(constants) + len(enum_values)
    for index, (name, arguments) in enumerate(HELPERS, start=helper_offset):
        value_name = f"nimValue{index}"
        expression = f"{name}({arguments})"
        lines.extend(
            [
                f"const {value_name} = uint64({expression})",
                "{.emit: [\"BGFXIM_STATIC_ASSERT((uint64_t)("
                f"{expression}) == \", {value_name}, "
                f"\", \\\"helper mismatch: {name}\\\");\"].}}",
            ]
        )

    lines.extend(
        [
            "",
            f'echo "value checks passed: {len(constants)} constants, " &',
            f'  "{len(enum_values)} enum values, {len(HELPERS)} helpers"',
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) != 4:
        raise SystemExit(__doc__)
    binding_path = Path(sys.argv[1])
    defines_path = Path(sys.argv[2])
    output_path = Path(sys.argv[3])
    constants = names(CONSTANT, defines_path.read_text(encoding="utf-8"))
    enum_values = names(ENUM, binding_path.read_text(encoding="utf-8"))
    output_path.write_text(generate(constants, enum_values), encoding="utf-8")


if __name__ == "__main__":
    main()
