#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-2-Clause
"""Generate exhaustive C/Nim ABI assertions from bgfx.nim.

Usage: tools/generate_abi_test.py bgfx.nim tests/test_abi.nim
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path


OBJECT = re.compile(
    r'^  (?P<nim>[A-Za-z0-9_]+)\* \{\.importc: "(?P<c>[^"]+)", '
    r'.*\bcompleteStruct\b.*\.\} = object$'
)
FIELD = re.compile(r"^    (?P<name>`?[A-Za-z0-9_]+`?)\*:")
EXPECTED_OBJECTS = 40
EXPECTED_FIELDS = 418


@dataclass(frozen=True)
class ImportedObject:
    nim_name: str
    c_name: str
    fields: tuple[str, ...]


def parse_objects(binding: str) -> list[ImportedObject]:
    result: list[ImportedObject] = []
    current_nim: str | None = None
    current_c: str | None = None
    fields: list[str] = []

    def finish() -> None:
        nonlocal current_nim, current_c, fields
        if current_nim is not None and current_c is not None:
            result.append(ImportedObject(current_nim, current_c, tuple(fields)))
        current_nim = None
        current_c = None
        fields = []

    for line in binding.splitlines():
        object_match = OBJECT.match(line)
        if object_match:
            finish()
            current_nim = object_match.group("nim")
            current_c = object_match.group("c")
            continue

        if current_nim is None:
            continue

        if line.startswith("  ") and not line.startswith("    "):
            finish()
            continue

        field_match = FIELD.match(line)
        if field_match:
            fields.append(field_match.group("name").strip("`"))

    finish()
    return result


def generate(objects: list[ImportedObject]) -> str:
    field_count = sum(len(item.fields) for item in objects)
    if len(objects) != EXPECTED_OBJECTS:
        raise ValueError(
            f"expected {EXPECTED_OBJECTS} imported objects, found {len(objects)}"
        )
    if field_count != EXPECTED_FIELDS:
        raise ValueError(f"expected {EXPECTED_FIELDS} fields, found {field_count}")

    lines = [
        "# SPDX-License-Identifier: BSD-2-Clause",
        "# Generated by tools/generate_abi_test.py. Do not edit by hand.",
        "",
        "import bgfx",
        "",
        '{.emit: """',
        "#include <stddef.h>",
        "#include <bgfx/c99/bgfx.h>",
        "#if defined(__cplusplus)",
        "# define BGFXIM_STATIC_ASSERT(condition, message) static_assert(condition, message)",
        "# define BGFXIM_ALIGNOF(type) alignof(type)",
        "#else",
        "# define BGFXIM_STATIC_ASSERT(condition, message) _Static_assert(condition, message)",
        "# define BGFXIM_ALIGNOF(type) _Alignof(type)",
        "#endif",
        '""".}',
        "",
    ]

    assertion_index = 0
    for item in objects:
        size_name = f"nimSize{assertion_index}"
        align_name = f"nimAlign{assertion_index}"
        lines.extend(
            [
                f"const {size_name} = sizeof({item.nim_name})",
                f"const {align_name} = alignof({item.nim_name})",
                "{.emit: [\"BGFXIM_STATIC_ASSERT(sizeof("
                f"{item.c_name}) == \", {size_name}, \", \\\"size mismatch: "
                f"{item.c_name}\\\");\"].}}",
                "{.emit: [\"BGFXIM_STATIC_ASSERT(BGFXIM_ALIGNOF("
                f"{item.c_name}) == \", {align_name}, \", \\\"alignment mismatch: "
                f"{item.c_name}\\\");\"].}}",
            ]
        )
        assertion_index += 1

        for field in item.fields:
            offset_name = f"nimOffset{assertion_index}"
            # Quoting every field also covers Nim keywords such as `discard`.
            nim_field = f"`{field}`"
            lines.extend(
                [
                    f"const {offset_name} = offsetOf({item.nim_name}, {nim_field})",
                    "{.emit: [\"BGFXIM_STATIC_ASSERT(offsetof("
                    f"{item.c_name}, {field}) == \", {offset_name}, "
                    f"\", \\\"offset mismatch: {item.c_name}.{field}\\\");\"].}}",
                ]
            )
            assertion_index += 1
        lines.append("")

    lines.append(
        f'echo "ABI layout checks passed: {len(objects)} types, {field_count} fields"'
    )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    binding_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])
    objects = parse_objects(binding_path.read_text(encoding="utf-8"))
    output_path.write_text(generate(objects), encoding="utf-8")


if __name__ == "__main__":
    main()
